// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AssertionClassifier.proto

package edu.uw.bhi.bionlp.covid.parser.assertionclassifier;

public final class AssertionClassifierOuterClass {
  private AssertionClassifierOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AssertionClassifierInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:covid.parser.AssertionClassifierInput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string text = 1;</code>
     */
    java.lang.String getText();
    /**
     * <code>string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <code>int32 start_char_index = 2;</code>
     */
    int getStartCharIndex();

    /**
     * <code>int32 end_char_index = 3;</code>
     */
    int getEndCharIndex();
  }
  /**
   * <pre>
   * Assertion Classifier
   * </pre>
   *
   * Protobuf type {@code covid.parser.AssertionClassifierInput}
   */
  public  static final class AssertionClassifierInput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:covid.parser.AssertionClassifierInput)
      AssertionClassifierInputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AssertionClassifierInput.newBuilder() to construct.
    private AssertionClassifierInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AssertionClassifierInput() {
      text_ = "";
      startCharIndex_ = 0;
      endCharIndex_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AssertionClassifierInput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              text_ = s;
              break;
            }
            case 16: {

              startCharIndex_ = input.readInt32();
              break;
            }
            case 24: {

              endCharIndex_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.internal_static_covid_parser_AssertionClassifierInput_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.internal_static_covid_parser_AssertionClassifierInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput.class, edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput.Builder.class);
    }

    public static final int TEXT_FIELD_NUMBER = 1;
    private volatile java.lang.Object text_;
    /**
     * <code>string text = 1;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_CHAR_INDEX_FIELD_NUMBER = 2;
    private int startCharIndex_;
    /**
     * <code>int32 start_char_index = 2;</code>
     */
    public int getStartCharIndex() {
      return startCharIndex_;
    }

    public static final int END_CHAR_INDEX_FIELD_NUMBER = 3;
    private int endCharIndex_;
    /**
     * <code>int32 end_char_index = 3;</code>
     */
    public int getEndCharIndex() {
      return endCharIndex_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, text_);
      }
      if (startCharIndex_ != 0) {
        output.writeInt32(2, startCharIndex_);
      }
      if (endCharIndex_ != 0) {
        output.writeInt32(3, endCharIndex_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, text_);
      }
      if (startCharIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, startCharIndex_);
      }
      if (endCharIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, endCharIndex_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput)) {
        return super.equals(obj);
      }
      edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput other = (edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput) obj;

      boolean result = true;
      result = result && getText()
          .equals(other.getText());
      result = result && (getStartCharIndex()
          == other.getStartCharIndex());
      result = result && (getEndCharIndex()
          == other.getEndCharIndex());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (37 * hash) + START_CHAR_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getStartCharIndex();
      hash = (37 * hash) + END_CHAR_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getEndCharIndex();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Assertion Classifier
     * </pre>
     *
     * Protobuf type {@code covid.parser.AssertionClassifierInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:covid.parser.AssertionClassifierInput)
        edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.internal_static_covid_parser_AssertionClassifierInput_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.internal_static_covid_parser_AssertionClassifierInput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput.class, edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput.Builder.class);
      }

      // Construct using edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        text_ = "";

        startCharIndex_ = 0;

        endCharIndex_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.internal_static_covid_parser_AssertionClassifierInput_descriptor;
      }

      public edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput getDefaultInstanceForType() {
        return edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput.getDefaultInstance();
      }

      public edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput build() {
        edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput buildPartial() {
        edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput result = new edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput(this);
        result.text_ = text_;
        result.startCharIndex_ = startCharIndex_;
        result.endCharIndex_ = endCharIndex_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput) {
          return mergeFrom((edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput other) {
        if (other == edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput.getDefaultInstance()) return this;
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        if (other.getStartCharIndex() != 0) {
          setStartCharIndex(other.getStartCharIndex());
        }
        if (other.getEndCharIndex() != 0) {
          setEndCharIndex(other.getEndCharIndex());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>string text = 1;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 1;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>string text = 1;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }

      private int startCharIndex_ ;
      /**
       * <code>int32 start_char_index = 2;</code>
       */
      public int getStartCharIndex() {
        return startCharIndex_;
      }
      /**
       * <code>int32 start_char_index = 2;</code>
       */
      public Builder setStartCharIndex(int value) {
        
        startCharIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 start_char_index = 2;</code>
       */
      public Builder clearStartCharIndex() {
        
        startCharIndex_ = 0;
        onChanged();
        return this;
      }

      private int endCharIndex_ ;
      /**
       * <code>int32 end_char_index = 3;</code>
       */
      public int getEndCharIndex() {
        return endCharIndex_;
      }
      /**
       * <code>int32 end_char_index = 3;</code>
       */
      public Builder setEndCharIndex(int value) {
        
        endCharIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 end_char_index = 3;</code>
       */
      public Builder clearEndCharIndex() {
        
        endCharIndex_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:covid.parser.AssertionClassifierInput)
    }

    // @@protoc_insertion_point(class_scope:covid.parser.AssertionClassifierInput)
    private static final edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput();
    }

    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AssertionClassifierInput>
        PARSER = new com.google.protobuf.AbstractParser<AssertionClassifierInput>() {
      public AssertionClassifierInput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AssertionClassifierInput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AssertionClassifierInput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AssertionClassifierInput> getParserForType() {
      return PARSER;
    }

    public edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierInput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AssertionClassifierOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:covid.parser.AssertionClassifierOutput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string prediction = 1;</code>
     */
    java.lang.String getPrediction();
    /**
     * <code>string prediction = 1;</code>
     */
    com.google.protobuf.ByteString
        getPredictionBytes();

    /**
     * <code>string error = 2;</code>
     */
    java.lang.String getError();
    /**
     * <code>string error = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrorBytes();
  }
  /**
   * Protobuf type {@code covid.parser.AssertionClassifierOutput}
   */
  public  static final class AssertionClassifierOutput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:covid.parser.AssertionClassifierOutput)
      AssertionClassifierOutputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AssertionClassifierOutput.newBuilder() to construct.
    private AssertionClassifierOutput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AssertionClassifierOutput() {
      prediction_ = "";
      error_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AssertionClassifierOutput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              prediction_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              error_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.internal_static_covid_parser_AssertionClassifierOutput_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.internal_static_covid_parser_AssertionClassifierOutput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput.class, edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput.Builder.class);
    }

    public static final int PREDICTION_FIELD_NUMBER = 1;
    private volatile java.lang.Object prediction_;
    /**
     * <code>string prediction = 1;</code>
     */
    public java.lang.String getPrediction() {
      java.lang.Object ref = prediction_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        prediction_ = s;
        return s;
      }
    }
    /**
     * <code>string prediction = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPredictionBytes() {
      java.lang.Object ref = prediction_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prediction_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERROR_FIELD_NUMBER = 2;
    private volatile java.lang.Object error_;
    /**
     * <code>string error = 2;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      }
    }
    /**
     * <code>string error = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPredictionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, prediction_);
      }
      if (!getErrorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, error_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPredictionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, prediction_);
      }
      if (!getErrorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, error_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput)) {
        return super.equals(obj);
      }
      edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput other = (edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput) obj;

      boolean result = true;
      result = result && getPrediction()
          .equals(other.getPrediction());
      result = result && getError()
          .equals(other.getError());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PREDICTION_FIELD_NUMBER;
      hash = (53 * hash) + getPrediction().hashCode();
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code covid.parser.AssertionClassifierOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:covid.parser.AssertionClassifierOutput)
        edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.internal_static_covid_parser_AssertionClassifierOutput_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.internal_static_covid_parser_AssertionClassifierOutput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput.class, edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput.Builder.class);
      }

      // Construct using edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        prediction_ = "";

        error_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.internal_static_covid_parser_AssertionClassifierOutput_descriptor;
      }

      public edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput getDefaultInstanceForType() {
        return edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput.getDefaultInstance();
      }

      public edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput build() {
        edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput buildPartial() {
        edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput result = new edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput(this);
        result.prediction_ = prediction_;
        result.error_ = error_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput) {
          return mergeFrom((edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput other) {
        if (other == edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput.getDefaultInstance()) return this;
        if (!other.getPrediction().isEmpty()) {
          prediction_ = other.prediction_;
          onChanged();
        }
        if (!other.getError().isEmpty()) {
          error_ = other.error_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object prediction_ = "";
      /**
       * <code>string prediction = 1;</code>
       */
      public java.lang.String getPrediction() {
        java.lang.Object ref = prediction_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          prediction_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string prediction = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPredictionBytes() {
        java.lang.Object ref = prediction_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          prediction_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string prediction = 1;</code>
       */
      public Builder setPrediction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        prediction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string prediction = 1;</code>
       */
      public Builder clearPrediction() {
        
        prediction_ = getDefaultInstance().getPrediction();
        onChanged();
        return this;
      }
      /**
       * <code>string prediction = 1;</code>
       */
      public Builder setPredictionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        prediction_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object error_ = "";
      /**
       * <code>string error = 2;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string error = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string error = 2;</code>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string error = 2;</code>
       */
      public Builder clearError() {
        
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <code>string error = 2;</code>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        error_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:covid.parser.AssertionClassifierOutput)
    }

    // @@protoc_insertion_point(class_scope:covid.parser.AssertionClassifierOutput)
    private static final edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput();
    }

    public static edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AssertionClassifierOutput>
        PARSER = new com.google.protobuf.AbstractParser<AssertionClassifierOutput>() {
      public AssertionClassifierOutput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AssertionClassifierOutput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AssertionClassifierOutput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AssertionClassifierOutput> getParserForType() {
      return PARSER;
    }

    public edu.uw.bhi.bionlp.covid.parser.assertionclassifier.AssertionClassifierOuterClass.AssertionClassifierOutput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_covid_parser_AssertionClassifierInput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_covid_parser_AssertionClassifierInput_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_covid_parser_AssertionClassifierOutput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_covid_parser_AssertionClassifierOutput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031AssertionClassifier.proto\022\014covid.parse" +
      "r\"Z\n\030AssertionClassifierInput\022\014\n\004text\030\001 " +
      "\001(\t\022\030\n\020start_char_index\030\002 \001(\005\022\026\n\016end_cha" +
      "r_index\030\003 \001(\005\">\n\031AssertionClassifierOutp" +
      "ut\022\022\n\nprediction\030\001 \001(\t\022\r\n\005error\030\002 \001(\t2|\n" +
      "\023AssertionClassifier\022e\n\020PredictAssertion" +
      "\022&.covid.parser.AssertionClassifierInput" +
      "\032\'.covid.parser.AssertionClassifierOutpu" +
      "t\"\000B4\n2edu.uw.bhi.bionlp.covid.parser.as" +
      "sertionclassifierb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_covid_parser_AssertionClassifierInput_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_covid_parser_AssertionClassifierInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_covid_parser_AssertionClassifierInput_descriptor,
        new java.lang.String[] { "Text", "StartCharIndex", "EndCharIndex", });
    internal_static_covid_parser_AssertionClassifierOutput_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_covid_parser_AssertionClassifierOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_covid_parser_AssertionClassifierOutput_descriptor,
        new java.lang.String[] { "Prediction", "Error", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
