version: '3'
services:
    open-nlp:
        build:
            context: open-nlp/
        environment:
            - OPENNLP_PORT=${OPENNLP_PORT}
        ports:
            - ${OPENNLP_PORT}:${OPENNLP_PORT}
        networks:
            default:
                aliases:
                    - open-nlp
    assertion-classifier:
        build:
            context: assertion-classifier/
        environment:
            - ASRTCLA_PORT=${ASRTCLA_PORT}
        ports:
            - ${ASRTCLA_PORT}:${ASRTCLA_PORT}
        networks:
            default:
                aliases:
                    - assertion-classifier
    metamap:
        build:
            context: metamap/
        environment: 
            - METAMAP_PORT=${METAMAP_PORT}
            - ASRTCLA_PORT=${ASRTCLA_PORT}
        ports:
            - ${METAMAP_PORT}:${METAMAP_PORT}
        networks:
            default:
                aliases:
                    - metamap
        depends_on:
            - open-nlp
            - assertion-classifier
networks:
    default:
        driver: bridge
