version: '3'
services:
    open-nlp:
        build:
            context: open-nlp/
        networks:
            default:
                aliases:
                    - open-nlp
    assertion-classifier:
        build:
            context: assertion-classifier/
        ports:
            - "8080:8080"
        networks:
            default:
                aliases:
                    - assertion-classifier
    metamap:
        build:
            context: metamap/
        ports:
            - "5000:5000"
        networks:
            default:
                aliases:
                    - metamap
        depends_on:
            - assertion-classifier

networks:
    default:
        driver: bridge
