// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OpenNLP.proto

package edu.uw.bhi.bionlp.covid.parser.opennlp;

public final class OpenNLPOuterClass {
  private OpenNLPOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SentenceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:covid.parser.Sentence)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>int32 begin_char_index = 2;</code>
     */
    int getBeginCharIndex();

    /**
     * <code>int32 end_char_index = 3;</code>
     */
    int getEndCharIndex();

    /**
     * <code>string text = 4;</code>
     */
    java.lang.String getText();
    /**
     * <code>string text = 4;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * <pre>
   * Sentence
   * </pre>
   *
   * Protobuf type {@code covid.parser.Sentence}
   */
  public  static final class Sentence extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:covid.parser.Sentence)
      SentenceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Sentence.newBuilder() to construct.
    private Sentence(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Sentence() {
      id_ = 0;
      beginCharIndex_ = 0;
      endCharIndex_ = 0;
      text_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Sentence(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              beginCharIndex_ = input.readInt32();
              break;
            }
            case 24: {

              endCharIndex_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              text_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.internal_static_covid_parser_Sentence_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.internal_static_covid_parser_Sentence_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence.class, edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int BEGIN_CHAR_INDEX_FIELD_NUMBER = 2;
    private int beginCharIndex_;
    /**
     * <code>int32 begin_char_index = 2;</code>
     */
    public int getBeginCharIndex() {
      return beginCharIndex_;
    }

    public static final int END_CHAR_INDEX_FIELD_NUMBER = 3;
    private int endCharIndex_;
    /**
     * <code>int32 end_char_index = 3;</code>
     */
    public int getEndCharIndex() {
      return endCharIndex_;
    }

    public static final int TEXT_FIELD_NUMBER = 4;
    private volatile java.lang.Object text_;
    /**
     * <code>string text = 4;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (beginCharIndex_ != 0) {
        output.writeInt32(2, beginCharIndex_);
      }
      if (endCharIndex_ != 0) {
        output.writeInt32(3, endCharIndex_);
      }
      if (!getTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, text_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (beginCharIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, beginCharIndex_);
      }
      if (endCharIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, endCharIndex_);
      }
      if (!getTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, text_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence)) {
        return super.equals(obj);
      }
      edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence other = (edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getBeginCharIndex()
          == other.getBeginCharIndex());
      result = result && (getEndCharIndex()
          == other.getEndCharIndex());
      result = result && getText()
          .equals(other.getText());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + BEGIN_CHAR_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getBeginCharIndex();
      hash = (37 * hash) + END_CHAR_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getEndCharIndex();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Sentence
     * </pre>
     *
     * Protobuf type {@code covid.parser.Sentence}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:covid.parser.Sentence)
        edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.internal_static_covid_parser_Sentence_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.internal_static_covid_parser_Sentence_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence.class, edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence.Builder.class);
      }

      // Construct using edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        beginCharIndex_ = 0;

        endCharIndex_ = 0;

        text_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.internal_static_covid_parser_Sentence_descriptor;
      }

      public edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence getDefaultInstanceForType() {
        return edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence.getDefaultInstance();
      }

      public edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence build() {
        edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence buildPartial() {
        edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence result = new edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence(this);
        result.id_ = id_;
        result.beginCharIndex_ = beginCharIndex_;
        result.endCharIndex_ = endCharIndex_;
        result.text_ = text_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence) {
          return mergeFrom((edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence other) {
        if (other == edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getBeginCharIndex() != 0) {
          setBeginCharIndex(other.getBeginCharIndex());
        }
        if (other.getEndCharIndex() != 0) {
          setEndCharIndex(other.getEndCharIndex());
        }
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int beginCharIndex_ ;
      /**
       * <code>int32 begin_char_index = 2;</code>
       */
      public int getBeginCharIndex() {
        return beginCharIndex_;
      }
      /**
       * <code>int32 begin_char_index = 2;</code>
       */
      public Builder setBeginCharIndex(int value) {
        
        beginCharIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 begin_char_index = 2;</code>
       */
      public Builder clearBeginCharIndex() {
        
        beginCharIndex_ = 0;
        onChanged();
        return this;
      }

      private int endCharIndex_ ;
      /**
       * <code>int32 end_char_index = 3;</code>
       */
      public int getEndCharIndex() {
        return endCharIndex_;
      }
      /**
       * <code>int32 end_char_index = 3;</code>
       */
      public Builder setEndCharIndex(int value) {
        
        endCharIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 end_char_index = 3;</code>
       */
      public Builder clearEndCharIndex() {
        
        endCharIndex_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>string text = 4;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 4;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 4;</code>
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>string text = 4;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:covid.parser.Sentence)
    }

    // @@protoc_insertion_point(class_scope:covid.parser.Sentence)
    private static final edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence();
    }

    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Sentence>
        PARSER = new com.google.protobuf.AbstractParser<Sentence>() {
      public Sentence parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Sentence(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Sentence> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Sentence> getParserForType() {
      return PARSER;
    }

    public edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SentenceDetectionInputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:covid.parser.SentenceDetectionInput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string text = 2;</code>
     */
    java.lang.String getText();
    /**
     * <code>string text = 2;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code covid.parser.SentenceDetectionInput}
   */
  public  static final class SentenceDetectionInput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:covid.parser.SentenceDetectionInput)
      SentenceDetectionInputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SentenceDetectionInput.newBuilder() to construct.
    private SentenceDetectionInput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SentenceDetectionInput() {
      id_ = "";
      text_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SentenceDetectionInput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              text_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.internal_static_covid_parser_SentenceDetectionInput_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.internal_static_covid_parser_SentenceDetectionInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput.class, edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEXT_FIELD_NUMBER = 2;
    private volatile java.lang.Object text_;
    /**
     * <code>string text = 2;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, text_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, text_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput)) {
        return super.equals(obj);
      }
      edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput other = (edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getText()
          .equals(other.getText());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code covid.parser.SentenceDetectionInput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:covid.parser.SentenceDetectionInput)
        edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.internal_static_covid_parser_SentenceDetectionInput_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.internal_static_covid_parser_SentenceDetectionInput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput.class, edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput.Builder.class);
      }

      // Construct using edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        text_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.internal_static_covid_parser_SentenceDetectionInput_descriptor;
      }

      public edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput getDefaultInstanceForType() {
        return edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput.getDefaultInstance();
      }

      public edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput build() {
        edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput buildPartial() {
        edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput result = new edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput(this);
        result.id_ = id_;
        result.text_ = text_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput) {
          return mergeFrom((edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput other) {
        if (other == edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>string text = 2;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 2;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 2;</code>
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>string text = 2;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:covid.parser.SentenceDetectionInput)
    }

    // @@protoc_insertion_point(class_scope:covid.parser.SentenceDetectionInput)
    private static final edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput();
    }

    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SentenceDetectionInput>
        PARSER = new com.google.protobuf.AbstractParser<SentenceDetectionInput>() {
      public SentenceDetectionInput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SentenceDetectionInput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SentenceDetectionInput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SentenceDetectionInput> getParserForType() {
      return PARSER;
    }

    public edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionInput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SentenceDetectionOutputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:covid.parser.SentenceDetectionOutput)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string text = 2;</code>
     */
    java.lang.String getText();
    /**
     * <code>string text = 2;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();

    /**
     * <code>repeated .covid.parser.Sentence sentences = 3;</code>
     */
    java.util.List<edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence> 
        getSentencesList();
    /**
     * <code>repeated .covid.parser.Sentence sentences = 3;</code>
     */
    edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence getSentences(int index);
    /**
     * <code>repeated .covid.parser.Sentence sentences = 3;</code>
     */
    int getSentencesCount();
    /**
     * <code>repeated .covid.parser.Sentence sentences = 3;</code>
     */
    java.util.List<? extends edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceOrBuilder> 
        getSentencesOrBuilderList();
    /**
     * <code>repeated .covid.parser.Sentence sentences = 3;</code>
     */
    edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceOrBuilder getSentencesOrBuilder(
        int index);

    /**
     * <code>repeated string errors = 4;</code>
     */
    java.util.List<java.lang.String>
        getErrorsList();
    /**
     * <code>repeated string errors = 4;</code>
     */
    int getErrorsCount();
    /**
     * <code>repeated string errors = 4;</code>
     */
    java.lang.String getErrors(int index);
    /**
     * <code>repeated string errors = 4;</code>
     */
    com.google.protobuf.ByteString
        getErrorsBytes(int index);
  }
  /**
   * Protobuf type {@code covid.parser.SentenceDetectionOutput}
   */
  public  static final class SentenceDetectionOutput extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:covid.parser.SentenceDetectionOutput)
      SentenceDetectionOutputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SentenceDetectionOutput.newBuilder() to construct.
    private SentenceDetectionOutput(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SentenceDetectionOutput() {
      id_ = "";
      text_ = "";
      sentences_ = java.util.Collections.emptyList();
      errors_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SentenceDetectionOutput(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              text_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                sentences_ = new java.util.ArrayList<edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence>();
                mutable_bitField0_ |= 0x00000004;
              }
              sentences_.add(
                  input.readMessage(edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence.parser(), extensionRegistry));
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                errors_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              errors_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          sentences_ = java.util.Collections.unmodifiableList(sentences_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          errors_ = errors_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.internal_static_covid_parser_SentenceDetectionOutput_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.internal_static_covid_parser_SentenceDetectionOutput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput.class, edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEXT_FIELD_NUMBER = 2;
    private volatile java.lang.Object text_;
    /**
     * <code>string text = 2;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENTENCES_FIELD_NUMBER = 3;
    private java.util.List<edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence> sentences_;
    /**
     * <code>repeated .covid.parser.Sentence sentences = 3;</code>
     */
    public java.util.List<edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence> getSentencesList() {
      return sentences_;
    }
    /**
     * <code>repeated .covid.parser.Sentence sentences = 3;</code>
     */
    public java.util.List<? extends edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceOrBuilder> 
        getSentencesOrBuilderList() {
      return sentences_;
    }
    /**
     * <code>repeated .covid.parser.Sentence sentences = 3;</code>
     */
    public int getSentencesCount() {
      return sentences_.size();
    }
    /**
     * <code>repeated .covid.parser.Sentence sentences = 3;</code>
     */
    public edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence getSentences(int index) {
      return sentences_.get(index);
    }
    /**
     * <code>repeated .covid.parser.Sentence sentences = 3;</code>
     */
    public edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceOrBuilder getSentencesOrBuilder(
        int index) {
      return sentences_.get(index);
    }

    public static final int ERRORS_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList errors_;
    /**
     * <code>repeated string errors = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getErrorsList() {
      return errors_;
    }
    /**
     * <code>repeated string errors = 4;</code>
     */
    public int getErrorsCount() {
      return errors_.size();
    }
    /**
     * <code>repeated string errors = 4;</code>
     */
    public java.lang.String getErrors(int index) {
      return errors_.get(index);
    }
    /**
     * <code>repeated string errors = 4;</code>
     */
    public com.google.protobuf.ByteString
        getErrorsBytes(int index) {
      return errors_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, text_);
      }
      for (int i = 0; i < sentences_.size(); i++) {
        output.writeMessage(3, sentences_.get(i));
      }
      for (int i = 0; i < errors_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, errors_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, text_);
      }
      for (int i = 0; i < sentences_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, sentences_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < errors_.size(); i++) {
          dataSize += computeStringSizeNoTag(errors_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getErrorsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput)) {
        return super.equals(obj);
      }
      edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput other = (edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getText()
          .equals(other.getText());
      result = result && getSentencesList()
          .equals(other.getSentencesList());
      result = result && getErrorsList()
          .equals(other.getErrorsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      if (getSentencesCount() > 0) {
        hash = (37 * hash) + SENTENCES_FIELD_NUMBER;
        hash = (53 * hash) + getSentencesList().hashCode();
      }
      if (getErrorsCount() > 0) {
        hash = (37 * hash) + ERRORS_FIELD_NUMBER;
        hash = (53 * hash) + getErrorsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code covid.parser.SentenceDetectionOutput}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:covid.parser.SentenceDetectionOutput)
        edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.internal_static_covid_parser_SentenceDetectionOutput_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.internal_static_covid_parser_SentenceDetectionOutput_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput.class, edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput.Builder.class);
      }

      // Construct using edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSentencesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        text_ = "";

        if (sentencesBuilder_ == null) {
          sentences_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          sentencesBuilder_.clear();
        }
        errors_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.internal_static_covid_parser_SentenceDetectionOutput_descriptor;
      }

      public edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput getDefaultInstanceForType() {
        return edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput.getDefaultInstance();
      }

      public edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput build() {
        edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput buildPartial() {
        edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput result = new edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.text_ = text_;
        if (sentencesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            sentences_ = java.util.Collections.unmodifiableList(sentences_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.sentences_ = sentences_;
        } else {
          result.sentences_ = sentencesBuilder_.build();
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          errors_ = errors_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.errors_ = errors_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput) {
          return mergeFrom((edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput other) {
        if (other == edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        if (sentencesBuilder_ == null) {
          if (!other.sentences_.isEmpty()) {
            if (sentences_.isEmpty()) {
              sentences_ = other.sentences_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureSentencesIsMutable();
              sentences_.addAll(other.sentences_);
            }
            onChanged();
          }
        } else {
          if (!other.sentences_.isEmpty()) {
            if (sentencesBuilder_.isEmpty()) {
              sentencesBuilder_.dispose();
              sentencesBuilder_ = null;
              sentences_ = other.sentences_;
              bitField0_ = (bitField0_ & ~0x00000004);
              sentencesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSentencesFieldBuilder() : null;
            } else {
              sentencesBuilder_.addAllMessages(other.sentences_);
            }
          }
        }
        if (!other.errors_.isEmpty()) {
          if (errors_.isEmpty()) {
            errors_ = other.errors_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureErrorsIsMutable();
            errors_.addAll(other.errors_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>string text = 2;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 2;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 2;</code>
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>string text = 2;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }

      private java.util.List<edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence> sentences_ =
        java.util.Collections.emptyList();
      private void ensureSentencesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          sentences_ = new java.util.ArrayList<edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence>(sentences_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence, edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence.Builder, edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceOrBuilder> sentencesBuilder_;

      /**
       * <code>repeated .covid.parser.Sentence sentences = 3;</code>
       */
      public java.util.List<edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence> getSentencesList() {
        if (sentencesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(sentences_);
        } else {
          return sentencesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .covid.parser.Sentence sentences = 3;</code>
       */
      public int getSentencesCount() {
        if (sentencesBuilder_ == null) {
          return sentences_.size();
        } else {
          return sentencesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .covid.parser.Sentence sentences = 3;</code>
       */
      public edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence getSentences(int index) {
        if (sentencesBuilder_ == null) {
          return sentences_.get(index);
        } else {
          return sentencesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .covid.parser.Sentence sentences = 3;</code>
       */
      public Builder setSentences(
          int index, edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence value) {
        if (sentencesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSentencesIsMutable();
          sentences_.set(index, value);
          onChanged();
        } else {
          sentencesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .covid.parser.Sentence sentences = 3;</code>
       */
      public Builder setSentences(
          int index, edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence.Builder builderForValue) {
        if (sentencesBuilder_ == null) {
          ensureSentencesIsMutable();
          sentences_.set(index, builderForValue.build());
          onChanged();
        } else {
          sentencesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .covid.parser.Sentence sentences = 3;</code>
       */
      public Builder addSentences(edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence value) {
        if (sentencesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSentencesIsMutable();
          sentences_.add(value);
          onChanged();
        } else {
          sentencesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .covid.parser.Sentence sentences = 3;</code>
       */
      public Builder addSentences(
          int index, edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence value) {
        if (sentencesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSentencesIsMutable();
          sentences_.add(index, value);
          onChanged();
        } else {
          sentencesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .covid.parser.Sentence sentences = 3;</code>
       */
      public Builder addSentences(
          edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence.Builder builderForValue) {
        if (sentencesBuilder_ == null) {
          ensureSentencesIsMutable();
          sentences_.add(builderForValue.build());
          onChanged();
        } else {
          sentencesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .covid.parser.Sentence sentences = 3;</code>
       */
      public Builder addSentences(
          int index, edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence.Builder builderForValue) {
        if (sentencesBuilder_ == null) {
          ensureSentencesIsMutable();
          sentences_.add(index, builderForValue.build());
          onChanged();
        } else {
          sentencesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .covid.parser.Sentence sentences = 3;</code>
       */
      public Builder addAllSentences(
          java.lang.Iterable<? extends edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence> values) {
        if (sentencesBuilder_ == null) {
          ensureSentencesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, sentences_);
          onChanged();
        } else {
          sentencesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .covid.parser.Sentence sentences = 3;</code>
       */
      public Builder clearSentences() {
        if (sentencesBuilder_ == null) {
          sentences_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          sentencesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .covid.parser.Sentence sentences = 3;</code>
       */
      public Builder removeSentences(int index) {
        if (sentencesBuilder_ == null) {
          ensureSentencesIsMutable();
          sentences_.remove(index);
          onChanged();
        } else {
          sentencesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .covid.parser.Sentence sentences = 3;</code>
       */
      public edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence.Builder getSentencesBuilder(
          int index) {
        return getSentencesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .covid.parser.Sentence sentences = 3;</code>
       */
      public edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceOrBuilder getSentencesOrBuilder(
          int index) {
        if (sentencesBuilder_ == null) {
          return sentences_.get(index);  } else {
          return sentencesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .covid.parser.Sentence sentences = 3;</code>
       */
      public java.util.List<? extends edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceOrBuilder> 
           getSentencesOrBuilderList() {
        if (sentencesBuilder_ != null) {
          return sentencesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(sentences_);
        }
      }
      /**
       * <code>repeated .covid.parser.Sentence sentences = 3;</code>
       */
      public edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence.Builder addSentencesBuilder() {
        return getSentencesFieldBuilder().addBuilder(
            edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence.getDefaultInstance());
      }
      /**
       * <code>repeated .covid.parser.Sentence sentences = 3;</code>
       */
      public edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence.Builder addSentencesBuilder(
          int index) {
        return getSentencesFieldBuilder().addBuilder(
            index, edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence.getDefaultInstance());
      }
      /**
       * <code>repeated .covid.parser.Sentence sentences = 3;</code>
       */
      public java.util.List<edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence.Builder> 
           getSentencesBuilderList() {
        return getSentencesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence, edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence.Builder, edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceOrBuilder> 
          getSentencesFieldBuilder() {
        if (sentencesBuilder_ == null) {
          sentencesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence, edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.Sentence.Builder, edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceOrBuilder>(
                  sentences_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          sentences_ = null;
        }
        return sentencesBuilder_;
      }

      private com.google.protobuf.LazyStringList errors_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureErrorsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          errors_ = new com.google.protobuf.LazyStringArrayList(errors_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string errors = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getErrorsList() {
        return errors_.getUnmodifiableView();
      }
      /**
       * <code>repeated string errors = 4;</code>
       */
      public int getErrorsCount() {
        return errors_.size();
      }
      /**
       * <code>repeated string errors = 4;</code>
       */
      public java.lang.String getErrors(int index) {
        return errors_.get(index);
      }
      /**
       * <code>repeated string errors = 4;</code>
       */
      public com.google.protobuf.ByteString
          getErrorsBytes(int index) {
        return errors_.getByteString(index);
      }
      /**
       * <code>repeated string errors = 4;</code>
       */
      public Builder setErrors(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureErrorsIsMutable();
        errors_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string errors = 4;</code>
       */
      public Builder addErrors(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureErrorsIsMutable();
        errors_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string errors = 4;</code>
       */
      public Builder addAllErrors(
          java.lang.Iterable<java.lang.String> values) {
        ensureErrorsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, errors_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string errors = 4;</code>
       */
      public Builder clearErrors() {
        errors_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string errors = 4;</code>
       */
      public Builder addErrorsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureErrorsIsMutable();
        errors_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:covid.parser.SentenceDetectionOutput)
    }

    // @@protoc_insertion_point(class_scope:covid.parser.SentenceDetectionOutput)
    private static final edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput();
    }

    public static edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SentenceDetectionOutput>
        PARSER = new com.google.protobuf.AbstractParser<SentenceDetectionOutput>() {
      public SentenceDetectionOutput parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SentenceDetectionOutput(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SentenceDetectionOutput> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SentenceDetectionOutput> getParserForType() {
      return PARSER;
    }

    public edu.uw.bhi.bionlp.covid.parser.opennlp.OpenNLPOuterClass.SentenceDetectionOutput getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_covid_parser_Sentence_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_covid_parser_Sentence_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_covid_parser_SentenceDetectionInput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_covid_parser_SentenceDetectionInput_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_covid_parser_SentenceDetectionOutput_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_covid_parser_SentenceDetectionOutput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rOpenNLP.proto\022\014covid.parser\"V\n\010Sentenc" +
      "e\022\n\n\002id\030\001 \001(\005\022\030\n\020begin_char_index\030\002 \001(\005\022" +
      "\026\n\016end_char_index\030\003 \001(\005\022\014\n\004text\030\004 \001(\t\"2\n" +
      "\026SentenceDetectionInput\022\n\n\002id\030\001 \001(\t\022\014\n\004t" +
      "ext\030\002 \001(\t\"n\n\027SentenceDetectionOutput\022\n\n\002" +
      "id\030\001 \001(\t\022\014\n\004text\030\002 \001(\t\022)\n\tsentences\030\003 \003(" +
      "\0132\026.covid.parser.Sentence\022\016\n\006errors\030\004 \003(" +
      "\t2i\n\007OpenNLP\022^\n\017DetectSentences\022$.covid." +
      "parser.SentenceDetectionInput\032%.covid.pa" +
      "rser.SentenceDetectionOutputB(\n&edu.uw.b",
      "hi.bionlp.covid.parser.opennlpb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_covid_parser_Sentence_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_covid_parser_Sentence_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_covid_parser_Sentence_descriptor,
        new java.lang.String[] { "Id", "BeginCharIndex", "EndCharIndex", "Text", });
    internal_static_covid_parser_SentenceDetectionInput_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_covid_parser_SentenceDetectionInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_covid_parser_SentenceDetectionInput_descriptor,
        new java.lang.String[] { "Id", "Text", });
    internal_static_covid_parser_SentenceDetectionOutput_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_covid_parser_SentenceDetectionOutput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_covid_parser_SentenceDetectionOutput_descriptor,
        new java.lang.String[] { "Id", "Text", "Sentences", "Errors", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
