# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import AssertionClassifier_pb2 as AssertionClassifier__pb2


class AssertionClassifierStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DetectSentences = channel.unary_unary(
        '/assertionclassifier.AssertionClassifier/DetectSentences',
        request_serializer=AssertionClassifier__pb2.SentenceDetectionInput.SerializeToString,
        response_deserializer=AssertionClassifier__pb2.SentenceDetectionOutput.FromString,
        )
    self.PredictAssertion = channel.unary_unary(
        '/assertionclassifier.AssertionClassifier/PredictAssertion',
        request_serializer=AssertionClassifier__pb2.AssertionClassifierInput.SerializeToString,
        response_deserializer=AssertionClassifier__pb2.AssertionClassifierOutput.FromString,
        )


class AssertionClassifierServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DetectSentences(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PredictAssertion(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AssertionClassifierServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DetectSentences': grpc.unary_unary_rpc_method_handler(
          servicer.DetectSentences,
          request_deserializer=AssertionClassifier__pb2.SentenceDetectionInput.FromString,
          response_serializer=AssertionClassifier__pb2.SentenceDetectionOutput.SerializeToString,
      ),
      'PredictAssertion': grpc.unary_unary_rpc_method_handler(
          servicer.PredictAssertion,
          request_deserializer=AssertionClassifier__pb2.AssertionClassifierInput.FromString,
          response_serializer=AssertionClassifier__pb2.AssertionClassifierOutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'assertionclassifier.AssertionClassifier', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
