# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import CovidWorker_pb2 as CovidWorker__pb2


class CovidWorkerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RunMetaMap = channel.unary_unary(
        '/covidworker.CovidWorker/RunMetaMap',
        request_serializer=CovidWorker__pb2.Payload.SerializeToString,
        response_deserializer=CovidWorker__pb2.Result.FromString,
        )
    self.RunCovidPredictor = channel.unary_unary(
        '/covidworker.CovidWorker/RunCovidPredictor',
        request_serializer=CovidWorker__pb2.Payload.SerializeToString,
        response_deserializer=CovidWorker__pb2.Result.FromString,
        )


class CovidWorkerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RunMetaMap(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RunCovidPredictor(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CovidWorkerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RunMetaMap': grpc.unary_unary_rpc_method_handler(
          servicer.RunMetaMap,
          request_deserializer=CovidWorker__pb2.Payload.FromString,
          response_serializer=CovidWorker__pb2.Result.SerializeToString,
      ),
      'RunCovidPredictor': grpc.unary_unary_rpc_method_handler(
          servicer.RunCovidPredictor,
          request_deserializer=CovidWorker__pb2.Payload.FromString,
          response_serializer=CovidWorker__pb2.Result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'covidworker.CovidWorker', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
