# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MetaMap/MetaMap.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.OpenNLP.python import OpenNLP_pb2 as OpenNLP_dot_OpenNLP__pb2

from proto.OpenNLP.python.OpenNLP_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='MetaMap/MetaMap.proto',
  package='covid.parser',
  syntax='proto3',
  serialized_options=b'\n&edu.uw.bhi.bionlp.covid.parser.metamap',
  serialized_pb=b'\n\x15MetaMap/MetaMap.proto\x12\x0c\x63ovid.parser\x1a\x15OpenNLP/OpenNLP.proto\"]\n\x0cMetaMapInput\x12\n\n\x02id\x18\x01 \x01(\t\x12)\n\tsentences\x18\x02 \x03(\x0b\x32\x16.covid.parser.Sentence\x12\x16\n\x0esemantic_types\x18\x03 \x03(\t\"\xec\x01\n\x0eMetaMapConcept\x12\x0b\n\x03\x63ui\x18\x01 \x01(\t\x12\x14\n\x0c\x63oncept_name\x18\x02 \x01(\t\x12\x15\n\rsource_phrase\x18\x03 \x01(\t\x12\x16\n\x0esemantic_label\x18\x04 \x01(\t\x12\x1d\n\x15\x62\x65gin_sent_char_index\x18\x05 \x01(\x05\x12\x1b\n\x13\x65nd_sent_char_index\x18\x06 \x01(\x05\x12\x1c\n\x14\x62\x65gin_doc_char_index\x18\x07 \x01(\x05\x12\x1a\n\x12\x65nd_doc_char_index\x18\x08 \x01(\x05\x12\x12\n\nprediction\x18\t \x01(\t\"\x8d\x01\n\x0fMetaMapSentence\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x18\n\x10\x62\x65gin_char_index\x18\x02 \x01(\x05\x12\x16\n\x0e\x65nd_char_index\x18\x03 \x01(\x05\x12\x0c\n\x04text\x18\x04 \x01(\t\x12.\n\x08\x63oncepts\x18\x05 \x03(\x0b\x32\x1c.covid.parser.MetaMapConcept\"]\n\rMetaMapOutput\x12\n\n\x02id\x18\x01 \x01(\t\x12\x30\n\tsentences\x18\x02 \x03(\x0b\x32\x1d.covid.parser.MetaMapSentence\x12\x0e\n\x06\x65rrors\x18\x03 \x03(\t2Z\n\x07MetaMap\x12O\n\x14\x45xtractNamedEntities\x12\x1a.covid.parser.MetaMapInput\x1a\x1b.covid.parser.MetaMapOutputB(\n&edu.uw.bhi.bionlp.covid.parser.metamapP\x00\x62\x06proto3'
  ,
  dependencies=[OpenNLP_dot_OpenNLP__pb2.DESCRIPTOR,],
  public_dependencies=[OpenNLP_dot_OpenNLP__pb2.DESCRIPTOR,])




_METAMAPINPUT = _descriptor.Descriptor(
  name='MetaMapInput',
  full_name='covid.parser.MetaMapInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='covid.parser.MetaMapInput.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sentences', full_name='covid.parser.MetaMapInput.sentences', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='semantic_types', full_name='covid.parser.MetaMapInput.semantic_types', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=155,
)


_METAMAPCONCEPT = _descriptor.Descriptor(
  name='MetaMapConcept',
  full_name='covid.parser.MetaMapConcept',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cui', full_name='covid.parser.MetaMapConcept.cui', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='concept_name', full_name='covid.parser.MetaMapConcept.concept_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_phrase', full_name='covid.parser.MetaMapConcept.source_phrase', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='semantic_label', full_name='covid.parser.MetaMapConcept.semantic_label', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='begin_sent_char_index', full_name='covid.parser.MetaMapConcept.begin_sent_char_index', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_sent_char_index', full_name='covid.parser.MetaMapConcept.end_sent_char_index', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='begin_doc_char_index', full_name='covid.parser.MetaMapConcept.begin_doc_char_index', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_doc_char_index', full_name='covid.parser.MetaMapConcept.end_doc_char_index', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prediction', full_name='covid.parser.MetaMapConcept.prediction', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=394,
)


_METAMAPSENTENCE = _descriptor.Descriptor(
  name='MetaMapSentence',
  full_name='covid.parser.MetaMapSentence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='covid.parser.MetaMapSentence.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='begin_char_index', full_name='covid.parser.MetaMapSentence.begin_char_index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_char_index', full_name='covid.parser.MetaMapSentence.end_char_index', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='covid.parser.MetaMapSentence.text', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='concepts', full_name='covid.parser.MetaMapSentence.concepts', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=538,
)


_METAMAPOUTPUT = _descriptor.Descriptor(
  name='MetaMapOutput',
  full_name='covid.parser.MetaMapOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='covid.parser.MetaMapOutput.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sentences', full_name='covid.parser.MetaMapOutput.sentences', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errors', full_name='covid.parser.MetaMapOutput.errors', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=540,
  serialized_end=633,
)

_METAMAPINPUT.fields_by_name['sentences'].message_type = OpenNLP_dot_OpenNLP__pb2._SENTENCE
_METAMAPSENTENCE.fields_by_name['concepts'].message_type = _METAMAPCONCEPT
_METAMAPOUTPUT.fields_by_name['sentences'].message_type = _METAMAPSENTENCE
DESCRIPTOR.message_types_by_name['MetaMapInput'] = _METAMAPINPUT
DESCRIPTOR.message_types_by_name['MetaMapConcept'] = _METAMAPCONCEPT
DESCRIPTOR.message_types_by_name['MetaMapSentence'] = _METAMAPSENTENCE
DESCRIPTOR.message_types_by_name['MetaMapOutput'] = _METAMAPOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetaMapInput = _reflection.GeneratedProtocolMessageType('MetaMapInput', (_message.Message,), {
  'DESCRIPTOR' : _METAMAPINPUT,
  '__module__' : 'MetaMap.MetaMap_pb2'
  # @@protoc_insertion_point(class_scope:covid.parser.MetaMapInput)
  })
_sym_db.RegisterMessage(MetaMapInput)

MetaMapConcept = _reflection.GeneratedProtocolMessageType('MetaMapConcept', (_message.Message,), {
  'DESCRIPTOR' : _METAMAPCONCEPT,
  '__module__' : 'MetaMap.MetaMap_pb2'
  # @@protoc_insertion_point(class_scope:covid.parser.MetaMapConcept)
  })
_sym_db.RegisterMessage(MetaMapConcept)

MetaMapSentence = _reflection.GeneratedProtocolMessageType('MetaMapSentence', (_message.Message,), {
  'DESCRIPTOR' : _METAMAPSENTENCE,
  '__module__' : 'MetaMap.MetaMap_pb2'
  # @@protoc_insertion_point(class_scope:covid.parser.MetaMapSentence)
  })
_sym_db.RegisterMessage(MetaMapSentence)

MetaMapOutput = _reflection.GeneratedProtocolMessageType('MetaMapOutput', (_message.Message,), {
  'DESCRIPTOR' : _METAMAPOUTPUT,
  '__module__' : 'MetaMap.MetaMap_pb2'
  # @@protoc_insertion_point(class_scope:covid.parser.MetaMapOutput)
  })
_sym_db.RegisterMessage(MetaMapOutput)


DESCRIPTOR._options = None

_METAMAP = _descriptor.ServiceDescriptor(
  name='MetaMap',
  full_name='covid.parser.MetaMap',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=635,
  serialized_end=725,
  methods=[
  _descriptor.MethodDescriptor(
    name='ExtractNamedEntities',
    full_name='covid.parser.MetaMap.ExtractNamedEntities',
    index=0,
    containing_service=None,
    input_type=_METAMAPINPUT,
    output_type=_METAMAPOUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_METAMAP)

DESCRIPTOR.services_by_name['MetaMap'] = _METAMAP

# @@protoc_insertion_point(module_scope)
