# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto.MetaMap.python import MetaMap_pb2 as MetaMap_dot_MetaMap__pb2


class MetaMapStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ExtractNamedEntities = channel.unary_unary(
        '/covid.parser.MetaMap/ExtractNamedEntities',
        request_serializer=MetaMap_dot_MetaMap__pb2.MetaMapInput.SerializeToString,
        response_deserializer=MetaMap_dot_MetaMap__pb2.MetaMapOutput.FromString,
        )


class MetaMapServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ExtractNamedEntities(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MetaMapServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ExtractNamedEntities': grpc.unary_unary_rpc_method_handler(
          servicer.ExtractNamedEntities,
          request_deserializer=MetaMap_dot_MetaMap__pb2.MetaMapInput.FromString,
          response_serializer=MetaMap_dot_MetaMap__pb2.MetaMapOutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'covid.parser.MetaMap', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
