# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/MetaMap/MetaMap.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/MetaMap/MetaMap.proto',
  package='metamap',
  syntax='proto3',
  serialized_options=b'\n&edu.uw.bhi.bionlp.covid.parser.metamap',
  serialized_pb=b'\n\x1bproto/MetaMap/MetaMap.proto\x12\x07metamap\"(\n\x0cMetaMapInput\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\xec\x01\n\x0eMetaMapConcept\x12\x0b\n\x03\x63ui\x18\x01 \x01(\t\x12\x14\n\x0c\x63oncept_name\x18\x02 \x01(\t\x12\x15\n\rsource_phrase\x18\x03 \x01(\t\x12\x16\n\x0esemantic_label\x18\x04 \x01(\t\x12\x1d\n\x15\x62\x65gin_sent_char_index\x18\x05 \x01(\x05\x12\x1b\n\x13\x65nd_sent_char_index\x18\x06 \x01(\x05\x12\x1c\n\x14\x62\x65gin_doc_char_index\x18\x07 \x01(\x05\x12\x1a\n\x12\x65nd_doc_char_index\x18\x08 \x01(\x05\x12\x12\n\nprediction\x18\t \x01(\t\"\x88\x01\n\x0fMetaMapSentence\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x18\n\x10\x62\x65gin_char_index\x18\x02 \x01(\x05\x12\x16\n\x0e\x65nd_char_index\x18\x03 \x01(\x05\x12\x0c\n\x04text\x18\x04 \x01(\t\x12)\n\x08\x63oncepts\x18\x05 \x03(\x0b\x32\x17.metamap.MetaMapConcept\"V\n\rMetaMapOutput\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12+\n\tsentences\x18\x03 \x03(\x0b\x32\x18.metamap.MetaMapSentence2R\n\x07MetaMap\x12G\n\x14\x45xtractNamedEntities\x12\x15.metamap.MetaMapInput\x1a\x16.metamap.MetaMapOutput\"\x00\x42(\n&edu.uw.bhi.bionlp.covid.parser.metamapb\x06proto3'
)




_METAMAPINPUT = _descriptor.Descriptor(
  name='MetaMapInput',
  full_name='metamap.MetaMapInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='metamap.MetaMapInput.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='metamap.MetaMapInput.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=80,
)


_METAMAPCONCEPT = _descriptor.Descriptor(
  name='MetaMapConcept',
  full_name='metamap.MetaMapConcept',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cui', full_name='metamap.MetaMapConcept.cui', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='concept_name', full_name='metamap.MetaMapConcept.concept_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_phrase', full_name='metamap.MetaMapConcept.source_phrase', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='semantic_label', full_name='metamap.MetaMapConcept.semantic_label', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='begin_sent_char_index', full_name='metamap.MetaMapConcept.begin_sent_char_index', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_sent_char_index', full_name='metamap.MetaMapConcept.end_sent_char_index', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='begin_doc_char_index', full_name='metamap.MetaMapConcept.begin_doc_char_index', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_doc_char_index', full_name='metamap.MetaMapConcept.end_doc_char_index', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prediction', full_name='metamap.MetaMapConcept.prediction', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=319,
)


_METAMAPSENTENCE = _descriptor.Descriptor(
  name='MetaMapSentence',
  full_name='metamap.MetaMapSentence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='metamap.MetaMapSentence.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='begin_char_index', full_name='metamap.MetaMapSentence.begin_char_index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_char_index', full_name='metamap.MetaMapSentence.end_char_index', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='metamap.MetaMapSentence.text', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='concepts', full_name='metamap.MetaMapSentence.concepts', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=458,
)


_METAMAPOUTPUT = _descriptor.Descriptor(
  name='MetaMapOutput',
  full_name='metamap.MetaMapOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='metamap.MetaMapOutput.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='metamap.MetaMapOutput.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sentences', full_name='metamap.MetaMapOutput.sentences', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=460,
  serialized_end=546,
)

_METAMAPSENTENCE.fields_by_name['concepts'].message_type = _METAMAPCONCEPT
_METAMAPOUTPUT.fields_by_name['sentences'].message_type = _METAMAPSENTENCE
DESCRIPTOR.message_types_by_name['MetaMapInput'] = _METAMAPINPUT
DESCRIPTOR.message_types_by_name['MetaMapConcept'] = _METAMAPCONCEPT
DESCRIPTOR.message_types_by_name['MetaMapSentence'] = _METAMAPSENTENCE
DESCRIPTOR.message_types_by_name['MetaMapOutput'] = _METAMAPOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MetaMapInput = _reflection.GeneratedProtocolMessageType('MetaMapInput', (_message.Message,), {
  'DESCRIPTOR' : _METAMAPINPUT,
  '__module__' : 'proto.MetaMap.MetaMap_pb2'
  # @@protoc_insertion_point(class_scope:metamap.MetaMapInput)
  })
_sym_db.RegisterMessage(MetaMapInput)

MetaMapConcept = _reflection.GeneratedProtocolMessageType('MetaMapConcept', (_message.Message,), {
  'DESCRIPTOR' : _METAMAPCONCEPT,
  '__module__' : 'proto.MetaMap.MetaMap_pb2'
  # @@protoc_insertion_point(class_scope:metamap.MetaMapConcept)
  })
_sym_db.RegisterMessage(MetaMapConcept)

MetaMapSentence = _reflection.GeneratedProtocolMessageType('MetaMapSentence', (_message.Message,), {
  'DESCRIPTOR' : _METAMAPSENTENCE,
  '__module__' : 'proto.MetaMap.MetaMap_pb2'
  # @@protoc_insertion_point(class_scope:metamap.MetaMapSentence)
  })
_sym_db.RegisterMessage(MetaMapSentence)

MetaMapOutput = _reflection.GeneratedProtocolMessageType('MetaMapOutput', (_message.Message,), {
  'DESCRIPTOR' : _METAMAPOUTPUT,
  '__module__' : 'proto.MetaMap.MetaMap_pb2'
  # @@protoc_insertion_point(class_scope:metamap.MetaMapOutput)
  })
_sym_db.RegisterMessage(MetaMapOutput)


DESCRIPTOR._options = None

_METAMAP = _descriptor.ServiceDescriptor(
  name='MetaMap',
  full_name='metamap.MetaMap',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=548,
  serialized_end=630,
  methods=[
  _descriptor.MethodDescriptor(
    name='ExtractNamedEntities',
    full_name='metamap.MetaMap.ExtractNamedEntities',
    index=0,
    containing_service=None,
    input_type=_METAMAPINPUT,
    output_type=_METAMAPOUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_METAMAP)

DESCRIPTOR.services_by_name['MetaMap'] = _METAMAP

# @@protoc_insertion_point(module_scope)
